Update call-action-mulitple-jobs-error-pattern.yaml

diff --git a/.github/workflows/call-action-mulitple-jobs-error-pattern.yaml b/.github/workflows/call-action-mulitple-jobs-error-pattern.yaml
--- a/.github/workflows/call-action-mulitple-jobs-error-pattern.yaml
+++ b/.github/workflows/call-action-mulitple-jobs-error-pattern.yaml
@@ -2,17 +2,28 @@ name: Call-Action outputs Summary
 
 on:
   workflow_dispatch:
+    inputs:
+      step-to-fail:
+        description: "which step to fail"
+        required: false
       
-
 jobs:
   start:
     name: Call Action
     runs-on: ubuntu-latest
     outputs:
-      errorStep: ${{ steps.action_id.outputs.error_step || ''}}
-      errorStepMessage: ${{ steps.action_id.outputs.error_step_message || ''}}
+      errorStep: ${{ steps.action_id.outputs.error_step || steps.step-1.outputs.error_step || ''}}
+      errorStepMessage: ${{ steps.action_id.outputs.error_step_message || steps.step-1.outputs.error_step_message || ''}}
     steps:
       - uses: actions/checkout@v2
+      - name: step 1
+        id: step-1
+        run: |  
+          if [[ ${{ github.event.inputs.step-to-fail }} == '1' ]]; then
+            echo "error_step=step-1" >> $GITHUB_OUTPUT
+            echo "error_step_message=step-2" >> $GITHUB_OUTPUT
+            exit 1
+          fi
       - id: action_id
         uses: ./.github/actions/return-action
         with:
